name: Testing Odd GitHub Behavior

on:
  pull_request:
    paths:
      - "packages/core/**"
    branches: [main]

jobs:
  build:
    name: Core - Build and Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        run: |
          cd packages/core
          bun run build:lib --ci
