name: Build React

on:
  pull_request:
    paths:
      - "packages/core/**"
      - "packages/react/**"
    branches: [main]

jobs:
  build:
    name: React - Build and Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install

      - name: Build core
        run: |
          cd packages/core
          bun run build:lib --ci

      - name: Build
        run: |
          cd packages/react
          bun run build --ci
